- name: install httpd
  action: yum name=httpd state=present

- name: restart httpd
  action: service name=httpd state=restarted

- name: install git
  command: yum install git -y

- name: pull code from github
  git:
    repo: "https://github.com/chandujalluri/samplecode.git"
    dest: "/var/www/html"
